CREATE TABLE startistics (
	id INTEGER NOT NULL AUTO_INCREMENT,
	artist VARCHAR(500) NOT NULL,
	facebook DOUBLE NOT NULL,
	twitter DOUBLE NOT NULL,
	instagram DOUBLE NOT NULL,
	youtube_sc DOUBLE NOT NULL,
	youtube_tuv DOUBLE NOT NULL DEFAULT 0,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;